[project]
drom-version = "0.1.0"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.07.0"
mode = "binary"
name = "opam-bin"
sphinx-target = "docs"
synopsis = "The opam-bin tool is a simple framework to use `opam` with binary packages"
version = "1.0.0"
windows-ci = true

# keys that you could also define:
# build-profile = "...build-profile..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
opam-binary is a simple framework to use `opam` with binary packages.
"""

[drom]
skip = "sphinx/_static/css/fixes.css sphinx/index.rst sphinx/conf.py docs/.nojekyll docs/index.html src/opam_bin_lib/main.ml src/opam_bin/main.ml CHANGES.md sphinx/install.rst sphinx/about.rst .github/workflows/doc-deploy.yml"

[dependencies]
ez_cmdliner = "0.1.0"
ez_config = "0.1.0"
ez_file = "0.2.0"
ezjsonm = "1.0.0"
ocplib-json-typed = "0.7.0"
opam-file-format = "2.0.0"
re = ">1.0"

[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]
generators = ["ocamllex", "ocamlyacc"]
pack-modules = true
skip-dirs = ["test2"]

[[package]]
dir = "src/opam_bin"

[[package]]
dir = "src/opam_bin_lib"

