(** Errors reported by the net-snmp library when sending/receiving a PDU *)
type t =
  | SNMP_ERR_NOERROR
  | SNMP_ERR_TOOBIG
  | SNMP_ERR_NOSUCHNAME
  | SNMP_ERR_BADVALUE
  | SNMP_ERR_READONLY
  | SNMP_ERR_GENERR
  | SNMP_ERR_NOACCESS
  | SNMP_ERR_WRONGTYPE
  | SNMP_ERR_WRONGLENGTH
  | SNMP_ERR_WRONGENCODING
  | SNMP_ERR_WRONGVALUE
  | SNMP_ERR_NOCREATION
  | SNMP_ERR_INCONSISTENTVALUE
  | SNMP_ERR_RESOURCEUNAVAILABLE
  | SNMP_ERR_COMMITFAILED
  | SNMP_ERR_UNDOFAILED
  | SNMP_ERR_AUTHORIZATIONERROR
  | SNMP_ERR_NOTWRITABLE
