#define SQLITE_ENABLE_COLUMN_METADATA 1
#define SQLITE_DEFAULT_FOREIGN_KEYS 1
#define SQLITE_DEFAULT_AUTO_VACUUM 1
#define SQLITE_ENABLE_JSON1 1
#define SQLITE_ENABLE_RTREE 1
#define SQLITE_ENABLE_SESSION 1
#define SQLITE_MAX_ATTACHED 125
#define SQLITE_THREADSAFE 2
