module Base_info = Bindings.Base_info.Enums(Bindings_stubs_base_info)
module Function_info = Bindings.Function_info.Flags(Bindings_stubs_function_info)
module Types = Bindings.Types.Enums(Bindings_stubs_types)
module VFunc_info = Bindings.VFunc_info.Flags(Bindings_stubs_vfunc_info)
module Arg_info = Bindings.Arg_info.Enums(Bindings_stubs_arg_info)
module Field_info = Bindings.Field_info.Flags(Bindings_stubs_field_info)
module GParam = Bindings.GParam.Flags(Bindings_stubs_g_param)
module GSignal = Bindings.GSignal.Flags(Bindings_stubs_g_signal)
