  $ electrod --na --pg $TESTDIR/relational.elo
  electrod* (glob)
  Processing file:* (glob)
  Generated file:
  --------------------------------------------------------------------------------
  -- Generated by electrod (C) ONERA * (glob)
  MODULE main
  JUSTICE TRUE;
  
  -- ((reflexive - iden) in none)
  INVAR
  TRUE;
  
  -- (symmetric = (~symmetric))
  INVAR
  TRUE;
  
  -- (tc_r = (^r))
  INVAR
  TRUE;
  
  -- ((s.(*r)) = (s.(iden + (^r))))
  INVAR
  TRUE;
  
  -- ((*r) = iden_plus_tc_r)
  INVAR
  TRUE;
  
  -- (iden_plus_tc_r = (iden + (^r)))
  INVAR
  TRUE;
  
  -- ((s.r) = ((~r).s))
  INVAR
  TRUE;
  
  -- ((^(~r)) = (~(^r)))
  INVAR
  TRUE;
  
  -- ((s <: (^r)) = s_proj_tc)
  INVAR
  TRUE;
  
  -- ((r ++ t) = r_overriden_by_t)
  INVAR
  TRUE;
  
  -- ((m ++ n) = m_plusplus_n)
  INVAR
  TRUE;
  
  -- ((s.r) = (s.r))
  INVAR
  TRUE;
  
  -- (not (eventually (some some/0 : z {true})))
  LTLSPEC
  !(F z-l);
  
  VAR z-l : boolean;
  --------------------------------------------------------------------------------
  Elapsed (wall-clock) time: * (glob)
