/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef NETSNMPVALUETEST_H
#define NETSNMPVALUETEST_H

/*
 * function declarations 
 */
void            init_netSnmpValueTest(void);
Netsnmp_Node_Handler handle_netSnmpValueTestInteger32;
Netsnmp_Node_Handler handle_netSnmpValueTestGauge;
Netsnmp_Node_Handler handle_netSnmpValueTestCounter;
Netsnmp_Node_Handler handle_netSnmpValueTestCounter64;
Netsnmp_Node_Handler handle_netSnmpValueTestTimeticks;
Netsnmp_Node_Handler handle_netSnmpValueTestUnsigned32;
Netsnmp_Node_Handler handle_netSnmpValueTestIpAddress;
Netsnmp_Node_Handler handle_netSnmpValueTestOpaque;
Netsnmp_Node_Handler handle_netSnmpValueTestObjectID;
Netsnmp_Node_Handler handle_netSnmpValueTestBitString;
Netsnmp_Node_Handler handle_netSnmpValueTestOctetString;
Netsnmp_Node_Handler handle_netSnmpValueTestOpaqueCounter64;
Netsnmp_Node_Handler handle_netSnmpValueTestOpaqueU64;
Netsnmp_Node_Handler handle_netSnmpValueTestOpaqueI64;
Netsnmp_Node_Handler handle_netSnmpValueTestOpaqueFloat;
Netsnmp_Node_Handler handle_netSnmpValueTestOpaqueDouble;

#endif                          /* NETSNMPVALUETEST_H */
