.PHONY: install uninstall reinstall

build: obmaccs
	dune build @install

clean:
	dune clean
	\rm -f *.eps *.scores *.toplot *.CDF *.ccurve src/ob_maccs \
	       *.{002,003,005,010,020}.txt

edit:
	emacs src/*.ml TODO commands.sh &

obmaccs:
	cd src; make

install:
	dune build @install
	dune install

uninstall:
	dune uninstall

reinstall: uninstall install

# unit tests
tests:
	qtest -o src/unit_tests.ml extract src/ROC.ml
	dune build src/unit_tests.exe
	_build/default/src/unit_tests.exe
	\rm -f _build/default/src/unit_tests.exe
	qtest -o src/unit_tests.ml extract src/myList.ml
	dune build src/unit_tests.exe
	_build/default/src/unit_tests.exe
	echo "(* DO NOT EDIT THIS FILE *)" > src/unit_tests.ml
