(* This file was generated. See dune file. *)

let list = [
  "WxWindows-exception-3.1";
  "Bootloader-exception";
  "PS-or-PDF-font-exception-20170817";
  "mif-exception";
  "OCCT-exception-1.0";
  "DigiRule-FOSS-exception";
  "OCaml-LGPL-linking-exception";
  "eCos-exception-2.0";
  "Linux-syscall-note";
  "u-boot-exception-2.0";
  "GPL-3.0-linking-source-exception";
  "Font-exception-2.0";
  "OpenJDK-assembly-exception-1.0";
  "GCC-exception-2.0";
  "389-exception";
  "SHL-2.0";
  "LZMA-exception";
  "FLTK-exception";
  "Autoconf-exception-2.0";
  "LLVM-exception";
  "Universal-FOSS-exception-1.0";
  "Fawkes-Runtime-exception";
  "freertos-exception-2.0";
  "Qt-LGPL-exception-1.1";
  "SHL-2.1";
  "Swift-exception";
  "GPL-3.0-linking-exception";
  "Qt-GPL-exception-1.0";
  "Libtool-exception";
  "Qwt-exception-1.0";
  "openvpn-openssl-exception";
  "GCC-exception-3.1";
  "Bison-exception-2.2";
  "Autoconf-exception-3.0";
  "gnu-javamail-exception";
  "Classpath-exception-2.0";
  "GPL-CC-1.0";
  "LGPL-3.0-linking-exception";
  "i2p-gpl-java-exception";
  "CLISP-exception-2.0";
]
